# Generated by Django 3.2.23 on 2024-03-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0003_auto_20240301_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_banktransactions',
            name='bank_to_bank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
