# Generated by Django 3.2.23 on 2024-03-02 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_fin_banktransactions_bank_to_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Purchase_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_gst_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_source_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.IntegerField(blank=True, null=True)),
                ('purchase_order_no', models.CharField(max_length=100)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_acc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_gst_type', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.IntegerField(default=0, null=True)),
                ('igst', models.FloatField(blank=True, default=0.0, null=True)),
                ('cgst', models.FloatField(blank=True, default=0.0, null=True)),
                ('sgst', models.FloatField(blank=True, default=0.0, null=True)),
                ('tax_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('adjustment', models.FloatField(blank=True, default=0.0, null=True)),
                ('shipping_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('grandtotal', models.FloatField(blank=True, default=0.0, null=True)),
                ('paid_off', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('file', models.FileField(default=None, null=True, upload_to='purchase_order')),
                ('status', models.CharField(default='Draft', max_length=150)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_vendors')),
            ],
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='fin_purchase_bill',
            name='porder_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.CreateModel(
            name='Fin_Purchase_Order_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.BigIntegerField()),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Purchase_Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_items')),
                ('PurchaseOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Purchase_Order_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('PurchaseOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Purchase_Order_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('PurchaseOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_purchase_order')),
            ],
        ),
        migrations.AddField(
            model_name='fin_purchase_order',
            name='converted_to_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_purchase_bill'),
        ),
        migrations.AddField(
            model_name='fin_purchase_order',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_company_payment_terms'),
        ),
    ]
