# Generated by Django 4.2.3 on 2024-03-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_alter_fin_salarydetails_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_salarydetails',
            name='conveyance_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
