# Generated by Django 4.2.3 on 2024-03-19 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_alter_fin_salarydetails_hra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name='fin_salarydetailshistory',
            name='action',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
    ]
